version: '3.8'

services:
  metadata-server:
    image: hochstenbach/metadata-server:v0.0.2
    container_name: metadata-server
    ports:
      - "3001:3001"
    depends_on:
      - zotero
    networks:
      - app-network
    volumes:
      - ./metadata-server/config:/app/config
      - ./metadata-server/error:/app/error
      - ./metadata-server/inbox:/app/inbox
      - ./metadata-server/outbox:/app/outbox

  zotero:
    image: zotero/translation-server:2.0.6
    container_name: zotero-translator
    ports:
      - "1969:1969"
    networks:
      - app-network

  wiki:
    image: hochstenbach/wiki-server:v0.0.1
    container_name: wiki-server
    ports:
      - "3000:3000"
    networks:
      - app-network
  
  postgres:
    image: postgres
    container_name: postgres-server
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data 

  eventlog-server:
    image: hochstenbach/eventlog-server:v0.0.1
    container_name: eventlog-server
    environment:
      POSTGRES_HOST: host.docker.internal
    depends_on:
      - postgres
    ports:
      - 3003:3003
    networks:
      - app-network

  claimbot-server:
    image: hochstenbach/claimbot-server:v0.0.1
    container_name: claimbot-server
    environment:
      MASTODON_URL: https://mas.to
      MASTODON_ACCESS_TOKEN: ${MASTODON_ACCESS_TOKEN}
      WIKIJS_URL: http://host.docker.internal:3000/graphql
      WIKIJS_ACCESS_TOKEN: ${WIKIJS_ACCESS_TOKEN}
      POSTGRES_HOST: host.docker.internal
    depends_on:
      - eventlog-server
    ports:
      - 3002:3002
    networks:
      - app-network
    volumes:
      - ./claimbot-server/config:/app/config
      - ./claimbot-server/accepted:/app/accepted
      - ./claimbox-server/error:/app/error
      - ./claimbot-server/inbox:/app/inbox
      - ./claimbot-server/outbox:/app/outbox

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
